import { NationalGridState } from '../types/client.js';

export async function getNationalGridStates(): Promise<NationalGridState[]> {
  return [
    {
      stateCode: 'MH',
      stateName: 'Maharashtra',
      activeFacilities: 3240,
      totalBeds: 24800,
      bedsOccupied: 17850,
      occupancyPct: 72,
      criticalAlertsCount: 4,
      avgStockCoverageDays: 14.8,
      coldChainCompliancePct: 98.4,
      readinessIndex: 91,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'GJ',
      stateName: 'Gujarat',
      activeFacilities: 2180,
      totalBeds: 16500,
      bedsOccupied: 10725,
      occupancyPct: 65,
      criticalAlertsCount: 2,
      avgStockCoverageDays: 18.2,
      coldChainCompliancePct: 99.1,
      readinessIndex: 94,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'KA',
      stateName: 'Karnataka',
      activeFacilities: 2640,
      totalBeds: 19800,
      bedsOccupied: 15440,
      occupancyPct: 78,
      criticalAlertsCount: 7,
      avgStockCoverageDays: 11.4,
      coldChainCompliancePct: 96.2,
      readinessIndex: 84,
      strategicBufferStatus: 'SURGE_WARNING',
    },
    {
      stateCode: 'KL',
      stateName: 'Kerala',
      activeFacilities: 1120,
      totalBeds: 14200,
      bedsOccupied: 11640,
      occupancyPct: 82,
      criticalAlertsCount: 3,
      avgStockCoverageDays: 16.5,
      coldChainCompliancePct: 99.5,
      readinessIndex: 92,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'TN',
      stateName: 'Tamil Nadu',
      activeFacilities: 2850,
      totalBeds: 22100,
      bedsOccupied: 15910,
      occupancyPct: 72,
      criticalAlertsCount: 3,
      avgStockCoverageDays: 17.1,
      coldChainCompliancePct: 98.8,
      readinessIndex: 93,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'AP',
      stateName: 'Andhra Pradesh',
      activeFacilities: 1920,
      totalBeds: 14800,
      bedsOccupied: 10950,
      occupancyPct: 74,
      criticalAlertsCount: 5,
      avgStockCoverageDays: 13.6,
      coldChainCompliancePct: 97.0,
      readinessIndex: 88,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'TS',
      stateName: 'Telangana',
      activeFacilities: 1450,
      totalBeds: 11200,
      bedsOccupied: 8170,
      occupancyPct: 73,
      criticalAlertsCount: 4,
      avgStockCoverageDays: 15.2,
      coldChainCompliancePct: 97.8,
      readinessIndex: 89,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'UP',
      stateName: 'Uttar Pradesh',
      activeFacilities: 4890,
      totalBeds: 38500,
      bedsOccupied: 32720,
      occupancyPct: 85,
      criticalAlertsCount: 14,
      avgStockCoverageDays: 8.7,
      coldChainCompliancePct: 92.4,
      readinessIndex: 76,
      strategicBufferStatus: 'EMERGENCY_MOBILIZATION',
    },
    {
      stateCode: 'RJ',
      stateName: 'Rajasthan',
      activeFacilities: 2410,
      totalBeds: 18200,
      bedsOccupied: 13830,
      occupancyPct: 76,
      criticalAlertsCount: 6,
      avgStockCoverageDays: 12.9,
      coldChainCompliancePct: 95.6,
      readinessIndex: 85,
      strategicBufferStatus: 'SURGE_WARNING',
    },
    {
      stateCode: 'MP',
      stateName: 'Madhya Pradesh',
      activeFacilities: 2280,
      totalBeds: 17400,
      bedsOccupied: 13570,
      occupancyPct: 78,
      criticalAlertsCount: 8,
      avgStockCoverageDays: 10.8,
      coldChainCompliancePct: 94.1,
      readinessIndex: 82,
      strategicBufferStatus: 'SURGE_WARNING',
    },
    {
      stateCode: 'WB',
      stateName: 'West Bengal',
      activeFacilities: 2580,
      totalBeds: 21500,
      bedsOccupied: 17630,
      occupancyPct: 82,
      criticalAlertsCount: 9,
      avgStockCoverageDays: 11.2,
      coldChainCompliancePct: 95.0,
      readinessIndex: 81,
      strategicBufferStatus: 'SURGE_WARNING',
    },
    {
      stateCode: 'BR',
      stateName: 'Bihar',
      activeFacilities: 2790,
      totalBeds: 20400,
      bedsOccupied: 17750,
      occupancyPct: 87,
      criticalAlertsCount: 16,
      avgStockCoverageDays: 7.9,
      coldChainCompliancePct: 91.8,
      readinessIndex: 73,
      strategicBufferStatus: 'EMERGENCY_MOBILIZATION',
    },
    {
      stateCode: 'OD',
      stateName: 'Odisha',
      activeFacilities: 1760,
      totalBeds: 13900,
      bedsOccupied: 9870,
      occupancyPct: 71,
      criticalAlertsCount: 4,
      avgStockCoverageDays: 14.5,
      coldChainCompliancePct: 96.7,
      readinessIndex: 87,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'PB',
      stateName: 'Punjab',
      activeFacilities: 1180,
      totalBeds: 9600,
      bedsOccupied: 6530,
      occupancyPct: 68,
      criticalAlertsCount: 2,
      avgStockCoverageDays: 19.0,
      coldChainCompliancePct: 98.9,
      readinessIndex: 94,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'HR',
      stateName: 'Haryana',
      activeFacilities: 1040,
      totalBeds: 8700,
      bedsOccupied: 5910,
      occupancyPct: 68,
      criticalAlertsCount: 2,
      avgStockCoverageDays: 18.4,
      coldChainCompliancePct: 98.5,
      readinessIndex: 93,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'AS',
      stateName: 'Assam',
      activeFacilities: 1340,
      totalBeds: 10200,
      bedsOccupied: 8060,
      occupancyPct: 79,
      criticalAlertsCount: 6,
      avgStockCoverageDays: 12.1,
      coldChainCompliancePct: 94.8,
      readinessIndex: 83,
      strategicBufferStatus: 'SURGE_WARNING',
    },
    {
      stateCode: 'DL',
      stateName: 'Delhi (NCT)',
      activeFacilities: 620,
      totalBeds: 15600,
      bedsOccupied: 12170,
      occupancyPct: 78,
      criticalAlertsCount: 3,
      avgStockCoverageDays: 21.0,
      coldChainCompliancePct: 99.4,
      readinessIndex: 95,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'JH',
      stateName: 'Jharkhand',
      activeFacilities: 1210,
      totalBeds: 9400,
      bedsOccupied: 7610,
      occupancyPct: 81,
      criticalAlertsCount: 7,
      avgStockCoverageDays: 9.8,
      coldChainCompliancePct: 93.2,
      readinessIndex: 78,
      strategicBufferStatus: 'SURGE_WARNING',
    },
    {
      stateCode: 'CG',
      stateName: 'Chhattisgarh',
      activeFacilities: 1150,
      totalBeds: 8900,
      bedsOccupied: 6410,
      occupancyPct: 72,
      criticalAlertsCount: 4,
      avgStockCoverageDays: 13.9,
      coldChainCompliancePct: 95.8,
      readinessIndex: 86,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'UK',
      stateName: 'Uttarakhand',
      activeFacilities: 680,
      totalBeds: 5400,
      bedsOccupied: 3780,
      occupancyPct: 70,
      criticalAlertsCount: 2,
      avgStockCoverageDays: 15.6,
      coldChainCompliancePct: 97.4,
      readinessIndex: 90,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'HP',
      stateName: 'Himachal Pradesh',
      activeFacilities: 590,
      totalBeds: 4800,
      bedsOccupied: 3120,
      occupancyPct: 65,
      criticalAlertsCount: 1,
      avgStockCoverageDays: 17.8,
      coldChainCompliancePct: 98.2,
      readinessIndex: 92,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'JK',
      stateName: 'Jammu & Kashmir',
      activeFacilities: 740,
      totalBeds: 6200,
      bedsOccupied: 4460,
      occupancyPct: 72,
      criticalAlertsCount: 3,
      avgStockCoverageDays: 14.1,
      coldChainCompliancePct: 96.5,
      readinessIndex: 88,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'GA',
      stateName: 'Goa',
      activeFacilities: 180,
      totalBeds: 1900,
      bedsOccupied: 1180,
      occupancyPct: 62,
      criticalAlertsCount: 0,
      avgStockCoverageDays: 22.4,
      coldChainCompliancePct: 99.8,
      readinessIndex: 97,
      strategicBufferStatus: 'HEALTHY',
    },
    {
      stateCode: 'TR',
      stateName: 'Tripura',
      activeFacilities: 240,
      totalBeds: 2100,
      bedsOccupied: 1510,
      occupancyPct: 72,
      criticalAlertsCount: 1,
      avgStockCoverageDays: 13.8,
      coldChainCompliancePct: 96.1,
      readinessIndex: 87,
      strategicBufferStatus: 'HEALTHY',
    },
  ];
}
